spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

cookie:
  secure: false
  same-site: Lax

management:
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
    logging:
      export:
        enabled: false

logging:
  level:
    waypoint.mvp: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.ai: DEBUG
