CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE blocks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id     VARCHAR(21)                             NOT NULL,
    memo            VARCHAR(2000),
    selected        BOOLEAN                                 NOT NULL,
    added_by_id     BIGINT                                  NOT NULL,
    place_id        BIGINT,
    social_media_id BIGINT,
    time_block_id   BIGINT                                  NOT NULL,
    CONSTRAINT blocks_pkey PRIMARY KEY (id)
);

CREATE TABLE budgets
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id    VARCHAR(21)                             NOT NULL,
    total_budget   BIGINT,
    traveler_count INTEGER,
    type           VARCHAR(255)                            NOT NULL,
    plan_id        BIGINT                                  NOT NULL,
    CONSTRAINT budgets_pkey PRIMARY KEY (id)
);

CREATE TABLE collection_members
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id   VARCHAR(21)                             NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    nickname      VARCHAR(255)                            NOT NULL,
    picture       VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    collection_id BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT collection_members_pkey PRIMARY KEY (id)
);

CREATE TABLE collection_place_drafts
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id          VARCHAR(21)                             NOT NULL,
    status               VARCHAR(255)                            NOT NULL,
    collection_member_id BIGINT                                  NOT NULL,
    social_media_id      BIGINT                                  NOT NULL,
    CONSTRAINT collection_place_drafts_pkey PRIMARY KEY (id)
);

CREATE TABLE collection_place_preferences
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    type                 VARCHAR(255)                            NOT NULL,
    collection_member_id BIGINT                                  NOT NULL,
    collection_place_id  BIGINT                                  NOT NULL,
    CONSTRAINT collection_place_preferences_pkey PRIMARY KEY (id)
);

CREATE TABLE collection_places
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id        VARCHAR(21)                             NOT NULL,
    memo               VARCHAR(2000),
    added_by_member_id BIGINT                                  NOT NULL,
    collection_id      BIGINT                                  NOT NULL,
    place_id           BIGINT                                  NOT NULL,
    social_media_id    BIGINT,
    CONSTRAINT collection_places_pkey PRIMARY KEY (id)
);

CREATE TABLE collections
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id  VARCHAR(21)                             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    member_count INTEGER                                 NOT NULL,
    thumbnail    VARCHAR(255)                            NOT NULL,
    title        VARCHAR(120)                            NOT NULL,
    CONSTRAINT collections_pkey PRIMARY KEY (id)
);

CREATE TABLE expense_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id VARCHAR(21)                             NOT NULL,
    cost        BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    expense_id  BIGINT                                  NOT NULL,
    CONSTRAINT expense_items_pkey PRIMARY KEY (id)
);

CREATE TABLE expenses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id   VARCHAR(21)                             NOT NULL,
    rank          BIGINT                                  NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    block_id      BIGINT,
    budget_id     BIGINT                                  NOT NULL,
    plan_day_id   BIGINT,
    time_block_id BIGINT,
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE place_block_opinion_tags
(
    block_opinions_id BIGINT NOT NULL,
    opinion_tag_id    VARCHAR(255)
);

CREATE TABLE place_block_opinions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id VARCHAR(21)                             NOT NULL,
    comment     VARCHAR(255)                            NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    added_by_id BIGINT                                  NOT NULL,
    block_id    BIGINT                                  NOT NULL,
    CONSTRAINT place_block_opinions_pkey PRIMARY KEY (id)
);

CREATE TABLE place_categories
(
    id        BIGINT NOT NULL,
    level     INTEGER,
    name      VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT place_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE place_category_mappings
(
    primary_type VARCHAR(255) NOT NULL,
    category_id  BIGINT,
    CONSTRAINT place_category_mappings_pkey PRIMARY KEY (primary_type)
);

CREATE TABLE place_extraction_jobs
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    decided_at           TIMESTAMP WITHOUT TIME ZONE,
    decision_status      VARCHAR(255)                            NOT NULL,
    job_id               VARCHAR(21)                             NOT NULL,
    collection_member_id BIGINT                                  NOT NULL,
    social_media_id      BIGINT                                  NOT NULL,
    CONSTRAINT place_extraction_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE places
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id     VARCHAR(21)                             NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    google_maps_uri VARCHAR(2048),
    photo_name      VARCHAR(512),
    place_id        VARCHAR(255)                            NOT NULL,
    primary_type    VARCHAR(100),
    location        GEOMETRY                                NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    photo_uri       VARCHAR(2048),
    category_id     BIGINT                                  NOT NULL,
    CONSTRAINT places_pkey PRIMARY KEY (id)
);

CREATE TABLE plan_collections
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id   VARCHAR(21)                             NOT NULL,
    collection_id BIGINT                                  NOT NULL,
    member_id     BIGINT                                  NOT NULL,
    plan_id       BIGINT                                  NOT NULL,
    CONSTRAINT plan_collections_pkey PRIMARY KEY (id)
);

CREATE TABLE plan_days
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    day        INTEGER                                 NOT NULL,
    plan_id    BIGINT                                  NOT NULL,
    CONSTRAINT plan_days_pkey PRIMARY KEY (id)
);

CREATE TABLE plan_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id VARCHAR(21)                             NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    nickname    VARCHAR(255)                            NOT NULL,
    picture     VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    plan_id     BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT plan_members_pkey PRIMARY KEY (id)
);

CREATE TABLE plans
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id  VARCHAR(21)                             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    end_date     date                                    NOT NULL,
    member_count INTEGER                                 NOT NULL,
    start_date   date                                    NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    CONSTRAINT plans_pkey PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE share_links
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    code               VARCHAR(255)                            NOT NULL,
    expires_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    host_user_id       BIGINT                                  NOT NULL,
    target_external_id VARCHAR(255)                            NOT NULL,
    target_id          BIGINT                                  NOT NULL,
    target_type        VARCHAR(255)                            NOT NULL,
    use_count          INTEGER                                 NOT NULL,
    CONSTRAINT share_links_pkey PRIMARY KEY (id)
);

CREATE TABLE social_media
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id  VARCHAR(21)                             NOT NULL,
    failure_code VARCHAR(255),
    snapshot     JSONB,
    status       VARCHAR(255)                            NOT NULL,
    summary      VARCHAR(255),
    type         VARCHAR(255)                            NOT NULL,
    url          VARCHAR(255)                            NOT NULL,
    CONSTRAINT social_media_pkey PRIMARY KEY (id)
);

CREATE TABLE social_media_places
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    failure_code    VARCHAR(255),
    search_query    VARCHAR(255)                            NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    place_id        BIGINT,
    social_media_id BIGINT                                  NOT NULL,
    CONSTRAINT social_media_places_pkey PRIMARY KEY (id)
);

CREATE TABLE time_blocks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    external_id VARCHAR(21)                             NOT NULL,
    end_time    time WITHOUT TIME ZONE                  NOT NULL,
    start_time  time WITHOUT TIME ZONE                  NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    plan_day_id BIGINT                                  NOT NULL,
    CONSTRAINT time_blocks_pkey PRIMARY KEY (id)
);

CREATE TABLE user_withdrawal_reasons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    reason     VARCHAR(2000)                           NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT user_withdrawal_reasons_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    nickname          VARCHAR(255)                            NOT NULL,
    picture           VARCHAR(255)                            NOT NULL,
    provider          VARCHAR(255)                            NOT NULL,
    provider_id       VARCHAR(255)                            NOT NULL,
    external_id       VARCHAR(21)                             NOT NULL,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    terms_accepted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);



-- ============================================
-- [CONSTRAINTS] UNIQUE KEYS
-- ============================================
ALTER TABLE collection_place_preferences
    ADD CONSTRAINT uq_collection_place_preferences_place_member UNIQUE (collection_place_id, collection_member_id);

ALTER TABLE expenses
    ADD CONSTRAINT uq_expenses_external_id UNIQUE (external_id);

ALTER TABLE expenses
    ADD CONSTRAINT uq_expenses_block_id UNIQUE (block_id);

ALTER TABLE plan_members
    ADD CONSTRAINT uq_plan_members_external_id UNIQUE (external_id);

ALTER TABLE plan_collections
    ADD CONSTRAINT uq_plan_collections_plan_collection UNIQUE (plan_id, collection_id);

ALTER TABLE budgets
    ADD CONSTRAINT uq_budgets_plan_id UNIQUE (plan_id);

ALTER TABLE users
    ADD CONSTRAINT uq_users_provider UNIQUE (provider, provider_id);

ALTER TABLE place_block_opinions
    ADD CONSTRAINT uq_place_block_opinions_block_member UNIQUE (block_id, added_by_id);

ALTER TABLE users
    ADD CONSTRAINT uq_users_external_id UNIQUE (external_id);

ALTER TABLE collections
    ADD CONSTRAINT uq_collections_external_id UNIQUE (external_id);

ALTER TABLE social_media
    ADD CONSTRAINT uq_social_media_external_id UNIQUE (external_id);

ALTER TABLE collection_members
    ADD CONSTRAINT uq_collection_members_external_id UNIQUE (external_id);

ALTER TABLE expense_items
    ADD CONSTRAINT uq_expense_items_external_id UNIQUE (external_id);

ALTER TABLE places
    ADD CONSTRAINT uq_places_external_id UNIQUE (external_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uq_refresh_tokens_token UNIQUE (token);

ALTER TABLE plans
    ADD CONSTRAINT uq_plans_external_id UNIQUE (external_id);

ALTER TABLE place_block_opinions
    ADD CONSTRAINT uq_place_block_opinions_external_id UNIQUE (external_id);

ALTER TABLE place_extraction_jobs
    ADD CONSTRAINT uq_place_extraction_jobs_job_id UNIQUE (job_id);

ALTER TABLE time_blocks
    ADD CONSTRAINT uq_time_blocks_external_id UNIQUE (external_id);

ALTER TABLE collection_place_drafts
    ADD CONSTRAINT uq_collection_place_drafts_member_social UNIQUE (collection_member_id, social_media_id);

ALTER TABLE collection_place_drafts
    ADD CONSTRAINT uq_collection_place_drafts_external_id UNIQUE (external_id);

ALTER TABLE plan_collections
    ADD CONSTRAINT uq_plan_collections_external_id UNIQUE (external_id);

ALTER TABLE collection_places
    ADD CONSTRAINT uq_collection_places_external_id UNIQUE (external_id);

ALTER TABLE budgets
    ADD CONSTRAINT uq_budgets_external_id UNIQUE (external_id);

ALTER TABLE blocks
    ADD CONSTRAINT uq_blocks_external_id UNIQUE (external_id);

ALTER TABLE social_media
    ADD CONSTRAINT uq_social_media_url UNIQUE (url);

ALTER TABLE places
    ADD CONSTRAINT uq_places_place_id UNIQUE (place_id);



-- ============================================
-- [CONSTRAINTS] FOREIGN KEYS
-- ============================================
ALTER TABLE budgets
    ADD CONSTRAINT fk_budgets_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE NO ACTION;

ALTER TABLE collection_place_preferences
    ADD CONSTRAINT fk_collection_place_preferences_member FOREIGN KEY (collection_member_id) REFERENCES collection_members (id) ON DELETE NO ACTION;

ALTER TABLE collection_places
    ADD CONSTRAINT fk_collection_places_added_by FOREIGN KEY (added_by_member_id) REFERENCES collection_members (id) ON DELETE NO ACTION;

ALTER TABLE place_extraction_jobs
    ADD CONSTRAINT fk_place_extraction_jobs_member FOREIGN KEY (collection_member_id) REFERENCES collection_members (id) ON DELETE NO ACTION;

ALTER TABLE plan_days
    ADD CONSTRAINT fk_plan_days_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE NO ACTION;

ALTER TABLE time_blocks
    ADD CONSTRAINT fk_time_blocks_plan_day FOREIGN KEY (plan_day_id) REFERENCES plan_days (id) ON DELETE CASCADE;

ALTER TABLE expense_items
    ADD CONSTRAINT fk_expense_items_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE;

ALTER TABLE place_block_opinions
    ADD CONSTRAINT fk_place_block_opinions_added_by FOREIGN KEY (added_by_id) REFERENCES plan_members (id) ON DELETE NO ACTION;

ALTER TABLE collection_places
    ADD CONSTRAINT fk_collection_places_collection FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE NO ACTION;

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_block FOREIGN KEY (block_id) REFERENCES blocks (id) ON DELETE CASCADE;

ALTER TABLE plan_collections
    ADD CONSTRAINT fk_plan_collections_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE NO ACTION;

ALTER TABLE collection_members
    ADD CONSTRAINT fk_collection_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE social_media_places
    ADD CONSTRAINT fk_social_media_places_place FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE NO ACTION;

ALTER TABLE social_media_places
    ADD CONSTRAINT fk_social_media_places_social_media FOREIGN KEY (social_media_id) REFERENCES social_media (id) ON DELETE NO ACTION;

ALTER TABLE blocks
    ADD CONSTRAINT fk_blocks_time_block FOREIGN KEY (time_block_id) REFERENCES time_blocks (id) ON DELETE CASCADE;

ALTER TABLE plan_collections
    ADD CONSTRAINT fk_plan_collections_member FOREIGN KEY (member_id) REFERENCES plan_members (id) ON DELETE NO ACTION;

ALTER TABLE place_category_mappings
    ADD CONSTRAINT fk_place_category_mappings_category FOREIGN KEY (category_id) REFERENCES place_categories (id) ON DELETE NO ACTION;

ALTER TABLE blocks
    ADD CONSTRAINT fk_blocks_added_by FOREIGN KEY (added_by_id) REFERENCES plan_members (id) ON DELETE NO ACTION;

ALTER TABLE blocks
    ADD CONSTRAINT fk_blocks_social_media FOREIGN KEY (social_media_id) REFERENCES social_media (id) ON DELETE NO ACTION;

ALTER TABLE collection_place_drafts
    ADD CONSTRAINT fk_collection_place_drafts_social_media FOREIGN KEY (social_media_id) REFERENCES social_media (id) ON DELETE NO ACTION;

ALTER TABLE place_categories
    ADD CONSTRAINT fk_place_categories_parent FOREIGN KEY (parent_id) REFERENCES place_categories (id) ON DELETE NO ACTION;

ALTER TABLE plan_members
    ADD CONSTRAINT fk_plan_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE collection_place_preferences
    ADD CONSTRAINT fk_collection_place_preferences_place FOREIGN KEY (collection_place_id) REFERENCES collection_places (id) ON DELETE CASCADE;

ALTER TABLE collection_places
    ADD CONSTRAINT fk_collection_places_social_media FOREIGN KEY (social_media_id) REFERENCES social_media (id) ON DELETE NO ACTION;

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_time_block FOREIGN KEY (time_block_id) REFERENCES time_blocks (id) ON DELETE NO ACTION;

ALTER TABLE place_block_opinion_tags
    ADD CONSTRAINT fk_place_block_opinion_tags_opinion FOREIGN KEY (block_opinions_id) REFERENCES place_block_opinions (id) ON DELETE CASCADE;

ALTER TABLE place_block_opinions
    ADD CONSTRAINT fk_place_block_opinions_block FOREIGN KEY (block_id) REFERENCES blocks (id) ON DELETE CASCADE;

ALTER TABLE plan_members
    ADD CONSTRAINT fk_plan_members_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE NO ACTION;

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_budget FOREIGN KEY (budget_id) REFERENCES budgets (id) ON DELETE NO ACTION;

ALTER TABLE plan_collections
    ADD CONSTRAINT fk_plan_collections_collection FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE NO ACTION;

ALTER TABLE place_extraction_jobs
    ADD CONSTRAINT fk_place_extraction_jobs_social_media FOREIGN KEY (social_media_id) REFERENCES social_media (id) ON DELETE NO ACTION;

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_plan_day FOREIGN KEY (plan_day_id) REFERENCES plan_days (id) ON DELETE CASCADE;

ALTER TABLE collection_place_drafts
    ADD CONSTRAINT fk_collection_place_drafts_member FOREIGN KEY (collection_member_id) REFERENCES collection_members (id) ON DELETE NO ACTION;

ALTER TABLE collection_places
    ADD CONSTRAINT fk_collection_places_place FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE NO ACTION;

ALTER TABLE collection_members
    ADD CONSTRAINT fk_collection_members_collection FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE NO ACTION;

ALTER TABLE blocks
    ADD CONSTRAINT fk_blocks_place FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE NO ACTION;
